# Generated by Django 3.0.3 on 2020-06-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_mdl',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
