# Generated by Django 3.0.3 on 2020-06-11 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_auto_20200611_1801'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register_mdl',
        ),
    ]
